version: '3.7'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_INSTANCE_NAME_A=Instance1
        - REDIS_URL=redis://localhost:6379
    environment:
      - PORT=3000
      - NEXT_PUBLIC_INSTANCE_NAME_A=Instance1
    depends_on:
      - redis
    ports:
      - '3001:3000'

  app2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_INSTANCE_NAME_B=Instance2
        - REDIS_URL=redis://localhost:6379
    environment:
      - PORT=3000
      - NEXT_PUBLIC_INSTANCE_NAME_B=Instance2
    depends_on:
      - redis
    ports:
      - '3002:3000'

  nginx:
    image: nginx:alpine
    ports:
      - '3000:3000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
